### ISSUE TITLE
http://127.0.0.1:4523/mock/934729/ 这个要怎么跑起来？

### ISSUE THREAD

**Issue by qingfengmy** [Flower-F/vue-element-admin#1]
http://127.0.0.1:4523/mock/934729/ 这个要怎么跑起来？现在前端项目跑起来，没有接口。

**Comment by Flower-F** [comment]
> http://127.0.0.1:4523/mock/934729/ 这个要怎么跑起来？现在前端项目跑起来，没有接口。

链接可以换成 https://mock.apifox.cn/m1/934729-0-default
